export enum ActionType {
  GET_MESSAGES = "GET_MESSAGES",
  GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS",
  GET_MESSAGES_ERROR = "GET_MESSAGES_ERROR",

  GET_MESSAGE = "GET_MESSAGE",
  GET_MESSAGE_SUCCESS = "GET_MESSAGE_SUCCESS",
  GET_MESSAGE_ERROR = "GET_MESSAGE_ERROR",
}
